// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgWMfkWufar2Jq-Zqx4QhiiX14ZzPjTR8',
    appId: '1:815277572520:web:5fd5ba35486b316a819d9d',
    messagingSenderId: '815277572520',
    projectId: 'gelirx-25b5d',
    authDomain: 'gelirx-25b5d.firebaseapp.com',
    storageBucket: 'gelirx-25b5d.appspot.com',
    measurementId: 'G-V64PT074QQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvVohKI5YcTgKYiWrf66nArsTWCHZyF6E',
    appId: '1:815277572520:android:9b1a01103818fb97819d9d',
    messagingSenderId: '815277572520',
    projectId: 'gelirx-25b5d',
    storageBucket: 'gelirx-25b5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV27fNVI_dDT9qydIu1mpn5MaWagx7Vqo',
    appId: '1:815277572520:ios:ad2fd3a86996103e819d9d',
    messagingSenderId: '815277572520',
    projectId: 'gelirx-25b5d',
    storageBucket: 'gelirx-25b5d.appspot.com',
    iosBundleId: 'com.aymerprime.gelirx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV27fNVI_dDT9qydIu1mpn5MaWagx7Vqo',
    appId: '1:815277572520:ios:ad2fd3a86996103e819d9d',
    messagingSenderId: '815277572520',
    projectId: 'gelirx-25b5d',
    storageBucket: 'gelirx-25b5d.appspot.com',
    iosBundleId: 'com.aymerprime.gelirx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgWMfkWufar2Jq-Zqx4QhiiX14ZzPjTR8',
    appId: '1:815277572520:web:84ece15e24c5cb9c819d9d',
    messagingSenderId: '815277572520',
    projectId: 'gelirx-25b5d',
    authDomain: 'gelirx-25b5d.firebaseapp.com',
    storageBucket: 'gelirx-25b5d.appspot.com',
    measurementId: 'G-KJQLWDNY6K',
  );
}
